### ISSUE TITLE
Clay Kiln causes large amounts of updates and cause TPS issues when items left inside.

### ISSUE THREAD

**Issue by Electrofried** [vadis365/PrimalTech#10]
Clay Kiln creates large amount of updates and causes TPS issues on server when an item is left inside the kiln.
![b6dbf6236e94bf970476535068daac3f](https://user-images.githubusercontent.com/27886155/37878446-f7edeaa4-30ac-11e8-9ded-6f3e843ea4cf.png)
--------------
Primal Tech Version: 0.2.98
--------------

**Comment by vadis365** [comment]
Hello,
I've changed a few things with the Kiln and have reduced the amount of block updates along with a few tweaks to the inventory handling. Hopefully this will bring the overhead down to a sane amount.
Let me know if this has helped with the TPS issues you are having.
Cheers,
Me.
