### ISSUE TITLE
[Improvement] Grill, Grindstone.

### ISSUE THREAD

**Issue by jursamaj** [vadis365/PrimalTech#15]
With the Grill, if you put something on it, you can't take it back off.  You end up having to break the grill to get it out.  This is very annoying if you accidentally put too much, or the wrong thing (especially as the grill will accept things it can't cook).  Clicking the source side with empty hand, or with anything other than what's already there should pick things up.

With the Grindstone, likewise, you can't remove source materials.  Also, you can't remove product materials until the entire source stack is used up.  attempting to just spins the stone.  There should be separate clicking areas for source, product, and grind.

**Comment by vadis365** [comment]
Try shift clicking with an empty hand - also the grindstone is not this mod, it's from Horse Power,

**Comment by jursamaj** [comment]
I tried left-click, shift left-click, right-click, and shift right-click, but none worked.  I eventually found that shift right-click worked, *but* only if there is nothing in the off hand. :/
