### ISSUE TITLE
Fluid bladder doesn't work with any fluid container

### ISSUE THREAD

**Issue by DragonmasterDJ** [vadis365/PrimalTech#17]
After making a fluid bladder. I got a primalCore barrel. and trying to right click on it with the bladder doesn't do anything. so I tried to grab a different one, like Extra Utils 2. doesn't work as well. 

solution / bug fix please?

**Comment by vadis365** [comment]
The fluid bladder works using forge fluid capabilities and works with tanks and barrels from many mods.
The issue is 100% not this mods fault, I have tested and used it with many mods and it works fine.
