### ISSUE TITLE
Visual Bug with automating the Clay Kiln 

### ISSUE THREAD

**Issue by Jandakast** [vadis365/PrimalTech#20]
If you automate the Clay Kiln using a Flame Grilled Wopper the last item processed will stay in the Kiln visually. This was originally reported to the SevTech tracker but this can be reproduced in a clean pack with only Primal Tech and JEI running.

Original Report: https://github.com/Darkosto/SevTech-Ages/issues/2232

Forge 2678
PrimalTech 0.3.2
jei 4.9.1.175

**Comment by vadis365** [comment]
Fixed in dev, will be in next update.
