### ISSUE TITLE
Forever Burning Stick Bundle

### ISSUE THREAD

**Issue by royalcw** [vadis365/PrimalTech#21]
So, I stacked two Stick Bundles up and lit the top bundle. The fire on top of the bottom bundle will burn forever like the Low Grade Charcoal without consuming the bottom bundle.

Minecraft 1.12.2
Forge 14.23.3.2679
Primal_Tech 0.3.2

**Comment by vadis365** [comment]
Added fire spread destruction to the block - will be in next update.
