### ISSUE TITLE
Workstump visual orientation hint

### ISSUE THREAD

**Issue by ZZaphodd** [vadis365/PrimalTech#25]
Hi, I'm playing sevtech and I feel primal tech new and fresh.

I had some trial and error using workstump.
obviously 3x3 recipes are orientation sensitive and there would be no issues with vanilla crafting table as they have gui and always show aligned orientation.

But workstump is placed on world and player sometime forgot(I did) its right orientation. And it look symmetric when looking down from top.
I was trying to craft some wooden slabs, and I bashed stone till the one wear out, but it was wrong recipe
right recipe
```
...
PPP
...
```
wrong recipe I tried
```
.P.
.P.
.P.
```

may I suggest an idea?
it would be better player could recognize top side(recipe) from looking work stump from top side(world)
or (mk2 works only) the number of placed item aligned to top side(recipe) instead of billboard way

**Comment by vadis365** [comment]
Hello,
The rock storage shelf is there for that exact reason. Store the rock on it and you will always know the orientation when you use it.
Cheers,
Me.
