### ISSUE TITLE
No possibily to create Whittled Fire Sticks with PrimalCore 1.12.2-0.6-57

### ISSUE THREAD

**Issue by Prelart** [vadis365/PrimalTech#28]
There is no possibily to create a Whittled Fire Sticks (#8165) with stick when updating the mod PrimalCore 1.12.2-0.6-57 and Primal Tech 0.3.3.

Sevtech 3.0.8, on 1.12.2

**Comment by vadis365** [comment]
Closing due to not being this mods responsibility.
