### ISSUE TITLE
Bone Knife uses different method then Flint Work Blade

### ISSUE THREAD

**Issue by CindyLouWho03** [vadis365/PrimalTech#30]
In my pack i renamed the Bone Knife to Bone Work Blade and added the ore dictionary to it of toolWorkBlade. But only the default primal core blades make the stripped logs. Primal tech one doesnt.

The catch is the Primal Tech one does but only if its the first craft, after its damaged doesn't madder.

Is one of them using NBT and the other using MetaData or am i mistaking something

**Comment by vadis365** [comment]
Hello,
I don't think what you are trying to do is possible as far as turning one item in to another from a different mod, the damage for the Bone Knife is indeed controlled by meta. I suspect you would need to iterate through all damage values or add a wildcard to the meta for what you are doing to possibly work.
Closing as this is something I probably wont be changeing - sorry.
Cheers,
Me.
