### ISSUE TITLE
Kiln destroys output item when a new item is inserted into it via hopper

### ISSUE THREAD

**Issue by justinrusso** [vadis365/PrimalTech#6]
Reference: https://github.com/Darkosto/SevTech-Ages/issues/689

**Comment by justinrusso** [comment]
My mistake, i should have tested to confirm. Could this be server only? I cannot replicate locally.

**Comment by justinrusso** [comment]
Im not sure it exactly consumes the output, but it starts processing another as if it was extracted.

**Comment by pennyvise1** [comment]
Setup
![2018-03-16_16 23 00](https://user-images.githubusercontent.com/6539792/37548633-8c0ceab0-2936-11e8-9a9a-b7aaf7dd35fc.png)

Stack in
![2018-03-16_16 23 47](https://user-images.githubusercontent.com/6539792/37548650-95f35dde-2936-11e8-853d-152cfa5959f9.png)

Run for a few minutes
![2018-03-16_16 25 35](https://user-images.githubusercontent.com/6539792/37548666-b2baf80a-2936-11e8-82f9-b4a8594da33a.png)

Single out

**Comment by vadis365** [comment]
fixed
