### ISSUE TITLE
Water powered saw doesn't work

### ISSUE THREAD

**Issue by Kazerima** [vadis365/PrimalTech#8]
I'm having trouble getting the saw to function. I've tried putting it above the source block, above the flowing block, backwards, forwards, blocks on either side, blocks on no sides, in the water itself, all without success. (this is in the 1.12 version using 1.12.2)

**Comment by vadis365** [comment]
Hello,
I can get it to work no problem - strange. I made a gif of it working a while back, maybe it will help you see the way it functions. I've not had much time to post any in depth descriptions of the mod and the way things work atm - but I will overhaul the curse page when I can get time and provide some better documentation. Above the source block of water with 1 flowing block behind, is how it's designed to work. Cutting the flowing block off stops the saw (in case people want rudimentary redstone control with a piston).

![saw functioning](https://user-images.githubusercontent.com/6518708/37780697-2cd2b196-2de7-11e8-8dea-a73aa8ca53ed.gif)

Cheers,
Me.

**Comment by Kazerima** [comment]
just solved the issue, turns out it has to be right on top of the source block placed against a block above the 1st flowing water block.
