### ISSUE TITLE
Crashloop due to Fire Sticks

### ISSUE THREAD

**Issue by blay09** [vadis365/PrimalTech#9]
Happened in SevTech. Crafted a fire stick and put it into my offhand, crafted another fire stick and put it in the slot that I had currently selected in my hotbar. Crashed, and trying to rejoin the world results in the same crash.

https://pastebin.com/g1xJSsFg

**Comment by cheesealmighty** [comment]
I'm experiencing the same error. It happened when I shift clicked as I was crafting fire sticks.
https://paste.ubuntu.com/p/nF3Kp2mwsb/

Should be fixable by NBTExplorer, @blay09 . But needs a long term solution, obviously.

**Comment by vadis365** [comment]
Hello,
Updates have been released which should address this issue - Closing for now, if this is happening in the latest at the time of writing this SevTech 3.0.2 please open a new issue.
Thanks for the report.
Cheers,
Me.
